#VALORES DEL PANEL POR DEFECTO
VPMAX_STC=40.0
IPMAX_STC=10.1
VOC_STC=48.7
ISC_STC=10.5
TEMP_STC=25
NOCT=44
TEMP_COEF_ISC=0.03
TEMP_COEF_IMP=-0.02
TEMP_COEF_VOC=-0.3
TEMP_COEF_VMP=-0.43
TEMP_COEF_PMAX=-0.38


#PARAMETROS DE PRUEBA POR DEFECTO
T2M_RANGE=18.75
ALLSKY_SFC_SW_DWN=400


#ALGORTIMO Y FORMULAS PARA OBTENCION DE POTENCIA Y AHORRO
T_CELL=T2M_RANGE+((NOCT-20)/(800))*ALLSKY_SFC_SW_DWN	                #TEMPERATURA DE LA CELDA
DELTA_T=T_CELL-TEMP_STC 		      		                                #DELTA DE TEMPERATURA
VOC=VOC_STC*(1+(TEMP_COEF_VOC/100)*DELTA_T)  		                      #VOLTAJE DE CIRCUITO ABIERTO
VMP=VPMAX_STC*(1+(TEMP_COEF_VMP/100)*DELTA_T) 		                    #VOLTAJE DE MAXIMA POTENCIA
ISC=ISC_STC*(1+(TEMP_COEF_ISC/100)*DELTA_T)   		                    #CORRIENTE DE CORTO CIRCUITO
IMP=IPMAX_STC*(1+(TEMP_COEF_IMP/100)*DELTA_T)		                      #CORRIENTE DE MAXIMA POTENCIA
FF=(VMP*IMP)/(VOC*ISC)					                                      #FEEL FACTOR
PMP=((VMP*IMP)/100)*12*30						                                  #PUNTO DE MAXIMA POTENCIA
DOLLAR=PMP*0.1
print(T_CELL)
print(DELTA_T)
print(VOC)
print(VMP)
print(ISC)
print(IMP)
print(FF)
print(PMP)
print(DOLLAR)


#NO ES NECESARIO INCLUIR TODAS LAS FORMULAS DENTRO DE LA APLICACION O PAGINA WEB, YA QUE NO SE REQUIERE
#TODOS LOS PARAMETROS SINO ALGUNOS EN ESPECIFICO

